# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'u.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1144, 750)
        MainWindow.setFixedSize(1144, 725)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.btnMarket = QtWidgets.QPushButton(self.centralwidget)
        self.btnMarket.setGeometry(QtCore.QRect(10, 10, 141, 51))
        self.btnMarket.setObjectName("btnMarket")
        self.btnPortfolio = QtWidgets.QPushButton(self.centralwidget)
        self.btnPortfolio.setGeometry(QtCore.QRect(190, 10, 131, 51))
        self.btnPortfolio.setObjectName("btnPortfolio")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 80, 1001, 601))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.verticalLayoutWidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.tableMarket = QtWidgets.QTableWidget(self.page_1)
        self.tableMarket.setGeometry(QtCore.QRect(0, 40, 791, 531))
        self.tableMarket.setObjectName("tableMarket")
        self.tableMarket.setColumnCount(5)
        self.tableMarket.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableMarket.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMarket.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMarket.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMarket.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableMarket.setHorizontalHeaderItem(4, item)

        self.tableMarket.horizontalHeader().setCascadingSectionResizes(True)
        self.labelMarket = QtWidgets.QLabel(self.page_1)
        self.labelMarket.setGeometry(QtCore.QRect(0, 0, 331, 41))
        self.labelMarket.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMarket.setObjectName("labelMarket")

        self.btnBuy = QtWidgets.QPushButton(self.page_1)
        self.btnBuy.setGeometry(QtCore.QRect(800, 170, 181, 81))
        self.btnBuy.setObjectName("btnBuy")

        self.addBtnMarket = QtWidgets.QPushButton(self.page_1)
        self.addBtnMarket.setGeometry(QtCore.QRect(840, 40, 91, 71))
        self.addBtnMarket.setObjectName("addBtnMarket")

        self.labelMarkovitzMarket = QtWidgets.QLabel(self.page_1)
        self.labelMarkovitzMarket.setGeometry(QtCore.QRect(790, 10, 191, 31))
        self.labelMarkovitzMarket.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMarkovitzMarket.setObjectName("labelMarkovitzMarket")

        self.analBtnMarket = QtWidgets.QPushButton(self.page_1)
        self.analBtnMarket.setGeometry(QtCore.QRect(800, 120, 181, 51))
        self.analBtnMarket.setObjectName("analBtnMarket")
        self.stackedWidget.addWidget(self.page_1)

        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")

        self.tablePortfolio = QtWidgets.QTableWidget(self.page_2)
        self.tablePortfolio.setGeometry(QtCore.QRect(0, 40, 791, 531))
        self.tablePortfolio.setObjectName("tablePortfolio")
        self.tablePortfolio.setColumnCount(6)
        self.tablePortfolio.setRowCount(0)

        item = QtWidgets.QTableWidgetItem()
        self.tablePortfolio.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePortfolio.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePortfolio.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePortfolio.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePortfolio.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tablePortfolio.setHorizontalHeaderItem(5, item)

        self.addBtnPortf = QtWidgets.QPushButton(self.page_2)
        self.addBtnPortf.setGeometry(QtCore.QRect(840, 40, 91, 71))
        self.addBtnPortf.setObjectName("addBtnPortf")

        self.analBtnPortf = QtWidgets.QPushButton(self.page_2)
        self.analBtnPortf.setGeometry(QtCore.QRect(800, 120, 181, 51))
        self.analBtnPortf.setObjectName("analBtnPortf")

        self.sellBtnPortf = QtWidgets.QPushButton(self.page_2)
        self.sellBtnPortf.setGeometry(QtCore.QRect(800, 170, 181, 81))
        self.sellBtnPortf.setObjectName("sellBtnPortf")

        self.labelPortf = QtWidgets.QLabel(self.page_2)
        self.labelPortf.setGeometry(QtCore.QRect(0, 0, 331, 31))
        self.labelPortf.setAlignment(QtCore.Qt.AlignCenter)
        self.labelPortf.setObjectName("labelPortf")

        self.labelMarkovitz_2 = QtWidgets.QLabel(self.page_2)
        self.labelMarkovitz_2.setGeometry(QtCore.QRect(790, 10, 191, 31))
        self.labelMarkovitz_2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelMarkovitz_2.setObjectName("labelMarkovitz_2")

        self.portfolioInfoButton = QtWidgets.QPushButton(self.page_2)
        self.portfolioInfoButton.setGeometry(QtCore.QRect(810, 350, 151, 81))
        self.portfolioInfoButton.setObjectName("portfolioInfoButton")

        self.stackedWidget.addWidget(self.page_2)
        self.verticalLayout.addWidget(self.stackedWidget)

        self.tableAnalysis = QtWidgets.QTableWidget(self.centralwidget)
        self.tableAnalysis.setGeometry(QtCore.QRect(1020, 80, 101, 191))
        self.tableAnalysis.setObjectName("tableAnalysis")
        self.tableAnalysis.setColumnCount(1)
        self.tableAnalysis.setRowCount(0)
        self.tableAnalysis.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)

        item = QtWidgets.QTableWidgetItem()
        self.tableAnalysis.setHorizontalHeaderItem(0, item)
        self.removeButton = QtWidgets.QPushButton(self.centralwidget)
        self.removeButton.setGeometry(QtCore.QRect(1020, 280, 101, 71))
        self.removeButton.setObjectName("removeButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1144, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnMarket.setText(_translate("MainWindow", "РЫНОК"))
        self.btnPortfolio.setText(_translate("MainWindow", "ПОРТФЕЛЬ"))

        item = self.tableMarket.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ТИКЕР"))
        item = self.tableMarket.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "НАЗВАНИЕ"))
        item = self.tableMarket.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ОТРАСЛЬ"))
        item = self.tableMarket.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ЦЕНА"))
        item = self.tableMarket.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "ТИП"))

        self.labelMarket.setText(_translate("MainWindow", "РЫНОК"))
        self.btnBuy.setText(_translate("MainWindow", "КУПИТЬ"))
        self.addBtnMarket.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.labelMarkovitzMarket.setText(_translate("MainWindow", "МАРКОВИЦ"))
        self.analBtnMarket.setText(_translate("MainWindow", "АНАЛИЗ"))
        item = self.tablePortfolio.horizontalHeaderItem(0)

        item.setText(_translate("MainWindow", "ТИКЕР"))
        item = self.tablePortfolio.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "НАЗВАНИЕ"))
        item = self.tablePortfolio.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "ОТРАСЛЬ"))
        item = self.tablePortfolio.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "ЦЕНА"))
        item = self.tablePortfolio.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "КОЛИЧЕСТВО"))
        item = self.tablePortfolio.horizontalHeaderItem(5)
        item.setText(_translate("MainWindow", "ТИП"))

        self.addBtnPortf.setText(_translate("MainWindow", "ДОБАВИТЬ"))
        self.analBtnPortf.setText(_translate("MainWindow", "АНАЛИЗ"))
        self.sellBtnPortf.setText(_translate("MainWindow", "ПРОДАТЬ"))
        self.labelPortf.setText(_translate("MainWindow", "ПОРТФЕЛЬ"))
        self.labelMarkovitz_2.setText(_translate("MainWindow", "МАРКОВИЦ"))
        self.portfolioInfoButton.setText(_translate("MainWindow", "О ПОРТФЕЛЕ"))

        item = self.tableAnalysis.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ТИКЕР"))
        self.removeButton.setText(_translate("MainWindow", "УБРАТЬ"))
